Fix extra issues groups
session-foundation/session-desktop pull request #20
Opened 2024-12-31 00:23 UTC by Bilb

2025-01-06 00:37 UTC, yougotwill requested changes

2025-01-06 00:37 UTC, yougotwill commented on ts/components/conversation/right-panel/overlay/OverlayRightPanelSettings.tsx
> +      onClick={() => void showDeleteGroupByConvoId(convoId, selectedUsername)}
Why has this one been changed?

2025-01-06 00:37 UTC, yougotwill commented on ts/hooks/useParamSelector.ts
> +    return libIsDestroyed || false;
Can you not use?

```suggestion
    return !!libIsDestroyed;
```

2025-01-06 00:37 UTC, yougotwill commented on ts/session/apis/snode_api/onions.ts
>  }) {
These keys seem to be used in a few places in different ways but with the same properties. See inside of `ts/session/apis/snode_api/onions.ts`,  I wonder if we should create a `WithX` types for them? Either per property or a combined type since they always seem to be together. Let me know what you think?

```tsx
{
  associatedWith?: string,
  destinationSnodeEd25519?: string
}
```

2025-01-06 00:37 UTC, yougotwill commented on ts/session/apis/snode_api/onions.ts
>  }) {
Not strictly related but in `processOnionResponse` I just noticed we have an `any` type for the status code. It might be good type it correctly? See line 602

```tsx
const status = jsonRes.status_code || jsonRes.status;
```

2025-01-06 00:37 UTC, yougotwill commented on ts/session/conversations/ConversationController.ts
> +    let failedToSent03LeaveMessage = true;
Just confirmed this is correct and not part of debugging / testing?

2025-01-06 00:37 UTC, yougotwill commented on ts/session/conversations/ConversationController.ts
> +    let failedToSent03LeaveMessage = true;
Never mind, I see you are assuming true unless we fail somehow. Then you set it to false.

2025-01-06 00:37 UTC, yougotwill commented on ts/session/utils/job_runners/jobs/GroupPendingRemovalsJob.ts
> +    const m = toUnrevoke[index];
Good catch. Much cleaner

2025-01-06 00:37 UTC, yougotwill commented on ts/components/conversation/right-panel/overlay/OverlayRightPanelSettings.tsx
> +      onClick={() => void showDeleteGroupByConvoId(convoId, selectedUsername)}
Actually I guess because you want to make sure this is a group 100% and also not send a leave message? 

I would have thought we would want to send a leave message?

2025-01-06 00:44 UTC, Bilb commented on ts/components/conversation/right-panel/overlay/OverlayRightPanelSettings.tsx
> +      onClick={() => void showDeleteGroupByConvoId(convoId, selectedUsername)}
we don't always want to send one. If we want to send one, that component (DeleteGroupPanelButton) won't be rendered but another one will. Does that make sense?

2025-01-06 01:00 UTC, Bilb commented on ts/session/apis/snode_api/onions.ts
>  }) {
I've made a few use the withs, but not all of them can be (like when they are not part of an object, but just args of a function, as a tuple). The others will need to be fixed as part of a bigger refactor.

2025-01-06 01:07 UTC, Bilb commented on ts/session/apis/snode_api/onions.ts
>  }) {
about the any, I added a `    // TODO: type those status
`

2025-01-06 03:51 UTC, yougotwill commented on ts/components/conversation/right-panel/overlay/OverlayRightPanelSettings.tsx
> +      onClick={() => void showDeleteGroupByConvoId(convoId, selectedUsername)}
Yup it does. Resolving

2025-01-06 03:54 UTC, yougotwill approved these changes
LGTM 🚢

2025-01-07 23:26 UTC, yougotwill approved these changes
LGTM 🚢

2025-01-09 02:47 UTC, yougotwill requested changes

2025-01-09 02:47 UTC, yougotwill commented on ts/components/MemberListItem.tsx
> +      return window.i18n('groupPendingRemoval'); // no text for those 3 pending removal states
There is now text so should the comment `// no text for those 3 pending removal states` be updated?

2025-01-09 02:47 UTC, yougotwill commented on ts/state/selectors/groups.ts
> +    // damn this is overkill
😂

2025-01-09 05:43 UTC, Bilb commented
merging this as last approved

2025-01-09 05:44 UTC, merged